export const RECIEVE_WORD_DEFINITION_PENDING = 'RECIEVE_WORD_DEFINITION_PENDING';
export const RECIEVE_WORD_DEFINITION_SUCCESS = 'RECIEVE_WORD_DEFINITION_SUCCESS';
export const RECIEVE_WORD_DEFINITION_ERROR = 'RECIEVE_WORD_DEFINITION_ERROR';
